### ISSUE TITLE
Patch Title 33 range ammdate

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#130]
Title 33 received_on `2019-07-17T19:30:09-0400` Volume 1's amendment date is `July 13-14, 2019`. This should be `July 14, 2019`

```yaml
patch: "July 13-14, 2019" -> "July 14, 2019"
starts_on: "2019-07-17"
ends_on: "2019-07-17"
```
<img width="429" alt="Screen Shot 2019-07-30 at 3 03 59 PM" src="https://user-images.githubusercontent.com/3782822/62168838-495e2780-b2db-11e9-9d7e-21be2fd36dc0.png">

Steve basecamp message:
https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/108715908/comments#401012955
