### ISSUE TITLE
Patch Title 47 ammdate month

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#131]
Title 47 Volume 5 had it's amendment date changed from `Dec. 12, 2018` to `Nov. 27, 2018` on 2019-02-05. This should be Dec. 27, 2018.

https://www.federalregister.gov/documents/2018/11/27/2018-24022/creation-of-interstitial-125-kilohertz-channels-in-the-800-mhz-band-between-809-817854-862-mhz

```
Printed version:
PDF

Publication Date:
11/27/2018

Agency:
Federal Communications Commission

Dates:
Effective Date: December 27, 2018.
```

```yaml
patch: "Nov. 27, 2018" -> "Dec. 27, 2018"
start_date: 2019-02-05
end_date: 2019-02-08
```

<img width="648" alt="Screen Shot 2019-07-30 at 3 35 56 PM" src="https://user-images.githubusercontent.com/3782822/62170501-6e08ce00-b2e0-11e9-9a00-1ded0db59468.png">
