### ISSUE TITLE
Patch Title 48 amendment date year

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#132]
On 2019-02-14 Title 48 Volume 4 had its amendment date go in reverse from `Nov. 14, 2018` to `Jan. 14, 2018`. This date should probably be 2019.

```yaml
patch: "Jan. 14, 2018" -> "Jan. 14, 2019"
starts_on: 2019-02-14
ends_on: 2019-02-20
```

<img width="608" alt="Screen Shot 2019-07-30 at 3 58 05 PM" src="https://user-images.githubusercontent.com/3782822/62171627-7531db00-b2e4-11e9-8b64-e893ba64976f.png">
